revproxy/response.py, revproxy/transformer.py
Only decoding content for transformations. This will avoid decoding huge
blobs saving a considerable amount of memory.
Closes #16
=> Reducing memory usage

revproxy/views.py, tests/test_request.py
This can be useful for proxying auto-reloading services during development, e.g.:
class CustomProxyView(ProxyView):
retries = Retry(backoff_factor=0.1)
upstream = 'http://localhost:12345'
=> Allow setting custom retries

revproxy/views.py
This was necessary to authenticate with a different username/password in the upstream (using basic auth).
I imagine it can be useful in other circumstances.
=> Add extension point for custom header adjustments

CHANGELOG.rst, revproxy/views.py, tests/test_views.py
This error was reported in #53.
Closes #53.
=> Fail to set upstream and diazo_rules when using as_view method

revproxy/connection.py, tests/test_connection.py, tests/test_pool.py
I noticed a small bug in your latest release... It looks like output in urllib3 (as processed by the new `_output()` method) is always a byte string, even when using Python3.
I've attached a fix that should resolve it, as well as some basic tests for that code, since it isn't covered currently.
=> Fix connections in Python 3

revproxy/transformer.py, tests/custom_diazo.xml, tests/test_transformer.py
When charset in Content-type HTTP header and the file encoding are different,
the unknown characters are ignored.
=> Fix transformation with wrong charset

revproxy/connection.py, revproxy/views.py
This adds support for custom `User` models which do not contain a `username` field: https://docs.djangoproject.com/en/1.10/ref/contrib/auth/#django.contrib.auth.models.User.get_username
=> User.get_username() rather than User.name to support custom User models

revproxy/views.py
To make it easier for subclasses to modify behavior.
=> Move construction of proxied path to method

.travis.yml, revproxy/response.py, revproxy/utils.py, revproxy/views.py, tests/test_utils.py, tests/test_views.py
This change permits cookie values to be quoted and contain equal signs, e.g.:
`_cookie_session="hello=world"`
=> Cookies with quotes

revproxy/views.py
This simply moves the *query parameter encoding* into it's own method so a sub-class can define how it should work.
For instance, the [OPeNDAP](https://www.opendap.org/) protocol supports queries like `http://example.com/file.nc?time[0:1:1]` but the current `urlencode` call encodes some characters that shouldn't be messed with.
A simple sub-class example:
```python
class ThreddsProxy(ProxyView):
def get_encoded_query_params(self):
get_data = encode_items(self.request.GET.lists())
encoded_query = urlencode(get_data, safe='[]:')
return encoded_query
```
=> Add get_encoded_query_params() 

revproxy/utils.py
=> remove empty headers from norm_headers

.travis.yml, revproxy/utils.py, revproxy/views.py, tests/test_utils.py
Modifies `utils.cookie_from_string()` to handle cookie values wrapped in double quotes.
Also:
- Fix flake8 complaining about invalid escape sequences
- Add Python 3.7 and Django 1.11 to Travis tests
=>  Handle quoted cookie values when `strict_cookies=False` 

revproxy/views.py
I'm terribly sorry @brianmay! :( This PR should fix the broken build: https://travis-ci.org/oktaal/django-revproxy. The import line became too long.
=> Import line was too long

docs/proxyview.rst, docs/quickstart.rst
As of Django 2, the urls.py uses a simple list for the URL patterns.
See https://docs.djangoproject.com/en/2.2/topics/http/urls/
=> Update docs for recent Django urlpatterns.

.pre-commit-config.yaml, .travis.yml
More can be added as required (see https://pre-commit.com/hooks.html), but this adds a basic pre-commit config file to stop the check erroring PRs (e.g. https://github.com/jazzband/django-revproxy/pull/130):
=> Add basic pre-commit config

README.rst, docs/introduction.rst, docs/proxyview.rst, revproxy/views.py, tests/test_request.py, tests/test_views.py
Closes #79
To remain backwards compatible, I decided to make it possible to enable with setting `add_x_forwarded` on the view.
`X-Forwarded-For` and `X-Forwarded-Proto` headers are required to be passed in by a lot of software that works with reverse proxies, including Keycloak for example.
=> Add `X-Forwarded-For` and `X-Forwarded-Proto` headers to request

README.rst
As mentioned at #129, the `README` file needed a Jazzband badge following the [guidelines](https://jazzband.co/about/guidelines#badges), this PR adds it.
=> Add Jazzband badge at README

revproxy/utils.py
This PR enables this package to be used with Python 3.10 in combination with Django 3.2+.
`getattr()` expects a default value in order for it not to return an exception.
Closes #147.
=> Fixed Header interface for Python 3.10

docs/proxyview.rst, revproxy/response.py, revproxy/views.py, tests/test_response.py
This PR:
- Make `streaming_amount` configurable via View class attribute
- Disable buffering when streaming "text/event-stream" response
More details can be found in code comments.
=> Make `streaming_amount` configurable via View class attribute

revproxy/views.py
This change was necessary to put Shiny apps behind a revproxy (it would return a 400 HTTP response).
=> Add "suppress_empty_body" configuration setting.

revproxy/utils.py, tests/test_utils.py
The list of valid cookie attributes is missing `SameSite`, and the `Max-Age`attribute should be spelled with a hyphen, not an underscore. These errors were causing cookies with these attributes set to be dropped when returned across the proxy:
Reference for attribute names:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie
=> Fix Valid Cookie Attribute List

revproxy/utils.py, tests/test_utils.py
Related to #150. The current code assumes that the cookie attributes have the same names as the arguments to the `set_cookie` function, but this isn't the case for `Max-Age` because the argument uses an underscore instead of a hyphen. This PR adds a special case for handling the `Max-Age` attribute.
=> Fix Mismatch in Max-Age Names

.github/workflows/test.yml, revproxy/transformer.py, setup.py, tests/urls.py, tox.ini
**Dropped**
- Drop support for python 2.7, 3.5 and 3.6. 
- Drop support for django 1.x and 2.x.
**Added**
- Add Support for python 3.11
- Added support for django 4.0 and 4.1
**Changes**
- Added `is_ajax` method to `DiazoTransformer` as it was deprecated from request object.
- Replaced old django url in favor of path.
=> Update python and django versions

.github/workflows/release.yml
A warning is displayed during release
```
Warning:  You are using "pypa/gh-action-pypi-publish@master". The "master" branch of this project has been sunset and will not receive any updates, not even security bug fixes. Please, make sure to use a supported version. If you want to pin to v1 major version, use "pypa/gh-action-pypi-publish@release/v1". If you feel adventurous, you may opt to use use "pypa/gh-action-pypi-publish@unstable/v1" instead. A more general recommendation is to pin to exact tags or commit shas.
```
Hope it gets fixed...
=> Avoided warning using release/v1 instead master

.github/workflows/release.yml, .github/workflows/test.yml
Fixes deprecation warnings:
actions/setup-python@v2
```
The following actions uses node12 which is deprecated and will be forced to run on node16: actions/checkout@v2, actions/setup-python@v2, actions/cache@v2, codecov/codecov-action@v2.0.3. For more info: https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/
```
set-output
```
The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
=> fix: Fixed deprecations in workflows and drop setup.py usages

docs/conf.py, docs/requirements.txt
In #177, readthedocs theme changed. This PR fixes that.
Before this PR:
After this PR:
=> Fixed sphinx theme

revproxy/views.py
May fix #183 deprecation warning. urrlib3 `response.headers` property is available in all versions supported by django-revproxy.
=> Replaced deprecated getheader in favor of headers

revproxy/utils.py, tests/test_utils.py
=> Cast int cookie dict max_age

.github/workflows/release.yml, .github/workflows/test.yml
Python 3.7 is not available anymore in `ubuntu-latest` image. Here it is the output of a failing test pipeline.
```
Run actions/setup-python@v4
with:
python-version: 3.7
cache: pip
cache-dependency-path: pyproject.toml
check-latest: false
token: ***
update-environment: true
allow-prereleases: false
Installed versions
Version 3.7 was not found in the local cache
Error: The version '3.7' with architecture 'x64' was not found for Ubuntu [2](https://github.com/jazzband/django-revproxy/actions/runs/13422519281/job/37498296312#step:3:2)4.04.
The list of all available versions can be found here: https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json
```
See https://github.com/actions/setup-python/issues/962#issuecomment-2414418045 for further information.
=> Enforce Ubuntu 22.04 in pipelines
